# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build CI

on: release

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    
    - uses: actions/checkout@v2
    
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    
    - name: Build
      run: |
        npm install
        npm run build
    
    - uses: actions/upload-artifact@v2
      with:
        name: wordpress-package.zip
        path: ./
